name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
      - run: npm run test

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm Install
      - run: npm run docs
