name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install
      - run: yarn run test
      - run: yarn run docs

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs'
          branch: docs
          message: 'docs\: New docs'
