name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: git checkout docs
      - run: npm install
      - run: npm run test
      - run: git add .
      - run: git commit -m "docs:\ New Docs"
      - run: git push
